### PR TITLE
Optimize Images

### PR DESCRIPTION
**Pull request by majouji**
## Purpose

Use [ImageOptim](https://imageoptim.com)’s **lossless optimization** to reduce raster image file sizes across the project without quality loss and optimize one SVG file using SVGO. Reduces project size and potentially bundle sizes as well without any quality loss or destruction.

34.6% overall gain, up to 86.6% per file.

## Changes

- Run all PNG images through ImageOptim
- Run `svgo --pretty --indent 2` on `script.svg` to optimize it

## See

Screen Shot 2020-03-07 at 12 11 57 AM

### CODE REVIEW

**Comment by majouji** [comment]
Excluded the images in tests – figured you wouldn’t want to alter those.

**Comment by gnachman** [comment]
Merged, thanks!

**Comment by majouji** [comment]
Looks like this was closed instead of merged; did you mean to do that? @gnachman

**Comment by gnachman** [comment]
I merged it manually to squash commits.

**Pull request closed without merging**
