### PR TITLE
Fix warnings introduced in Xcode 9

### PR DESCRIPTION
**Pull request by KarboniteKream**

### CODE REVIEW

**Comment by gnachman** [comment]
Thanks for the fix. Would you mind making the changes in `iTerm2/ColorPicker/ColorPicker` instead? The files you changed are in the build output of that project, which is only in the repo to keep build time fast.

**Comment by KarboniteKream** [comment]
Done!

**Comment by gnachman** [comment]
Thank you!

**Comment by gnachman** [comment]
I've built the framework and committed it in ccddc395f26494efb995cd87469a8736ebff0c69

**Pull request merged**
