### PR TITLE
Move travis to `osx_image: xcode8.1`.

### PR DESCRIPTION
**Pull request by phs**
This gives us macOS 10.12.1, which contains `NSTouchBar`.

### CODE REVIEW

**Comment by phs** [comment]
Worth a shot.

**Comment by gnachman** [comment]
Seems like a good idea, was there a problem with moving to 8.1?

**Comment by phs** [comment]
Yes.  I explored the problem over in #315.  In short the large majority of `PTYTextViewTest` tests fail due to a difference in font rendering, at least within the test suite.  If those could be fixed, then travis could move to 8.1 and be able to compile the touch bar support.

Notably when I just use the compiled binary directly, the fonts look the same as compared to a binary pulled down from homebrew.

**Comment by phs** [comment]
Note you can see travis failing those tests directly [in this PR's build](https://travis-ci.org/gnachman/iTerm2/builds/181028020)

**Pull request closed without merging**
