### PR TITLE
Do not warn multi line paste when the RemovingNewLines flag is true.

### PR DESCRIPTION
**Pull request by yilei**
The newlines will be removed when sanitizing.

### CODE REVIEW

**Comment by gnachman** [comment]
Hey @yilei ! Hope all's well with you. Thanks for the fix :)

**Comment by yilei** [comment]
All is well. I launched a new iOS app https://apps.apple.com/app/id1512238725 :)

Hope the same for you too, George. The new iTerm icon is tasty 😋

**Comment by gnachman** [comment]
Sounds like you had a baby? Congrats on the app and baby, if applicable :)

**Comment by yilei** [comment]
Oh right, she's turning two, thanks :)

**Pull request merged**
