### PR TITLE
imgls usage - fix to match the current script name

### PR DESCRIPTION
**Pull request by tskirvin**
imgls, not image.sh

### CODE REVIEW

**Comment by gnachman** [comment]
I actually just changed it to list the files in the current directory in this case.

**Comment by tskirvin** [comment]
Your patch doesn't work nicely with files with spaces in them (like, say, the upload directory from an iPhone into a Dropbox directory).  I don't know the right workaround off the top of my head, sorry...

**Comment by gnachman** [comment]
Good catch. Fixed in 508fc22.

**Comment by tskirvin** [comment]
Yep, that does the job.  Thanks!

**Pull request closed without merging**
