### PR TITLE
add: support Finder Services

### PR DESCRIPTION
**Pull request by liufsd**
I have add Finder Services.But i do not know how to invoke your "new tab or new window" method.
Thanks.

### CODE REVIEW

**Comment by gnachman** [comment]
I made a few tweaks. Please test it out and make sure it still works for you.

**Comment by liufsd** [comment]
Thanks.
Yes.It works.But i do not know how to open a tab ? I mean open a new tab in current window?

**Comment by liufsd** [comment]
And which version you will include this ?

**Comment by gnachman** [comment]
This is in the master branch so it will be in version 3.1. I'm not adding new features to 3.0 any more. I hope to put 3.1 into beta early next year.

**Pull request merged**
