### PR TITLE
Call malloc once instead of 3 times in CRunStorage everytime we alloc…

### PR DESCRIPTION
**Pull request by ronyfadel**
…ate elements

malloc is potentially called hundreds of times when clearing the display
This has the added advantage of reduced memory fragmentation

### CODE REVIEW

**Comment by gnachman** [comment]
Have you tried profiling to see if this makes a difference? I like avoiding calls to malloc but am concerned about adding extra complexity.

**Comment by ronyfadel** [comment]
I'm investigating iTerm's memory usage.. Found some low hanging fruits.
I should profile this, and report back.

**Comment by gnachman** [comment]
I ran some performance tests and didn't see a measurable difference. This was a good idea, but I think malloc is actually pretty fast compared to everything else that's going on during drawing so any benefit is dwarfed. This code is all going to go away in 3.1, anyway, so I'm going to close this out to avoid adding extra complexity.

**Comment by ronyfadel** [comment]
sure!

**Pull request closed without merging**
