### PR TITLE
Preliminary fixes for macOS Monterey

### PR DESCRIPTION
**Pull request by saagarjha**
iTerm will fail to build/crash at launch without these, so here are some very quick patches. Let me know if you would like these to be fixed in some other way.

### CODE REVIEW

**Comment by yanye666** [comment]
Can you provide ‘dmg’

**Comment by yanye666** [comment]
> iTerm will fail to build/crash at launch without these, so here are some very quick patches. Let me know if you would like these to be fixed in some other way.

Can you provide ‘./dmg’

**Review by Panajev — APPROVED** [review]

**Comment by Panajev** [comment]
@saagarjha  thanks, built it from source ( https://gitlab.com/gnachman/iterm2/wikis/HowToBuild @yanye666 ) using Xcode 13 Beta and I now have a binary I can run inside the application folder. PR review and kind of ... tested ;).

@gnachman could this be something going in the nightlies please?

**Comment by yanye666** [comment]
> @saagarjha 谢谢，使用Xcode 13 Beta从源代码（https://gitlab.com/gnachman/iterm2/wikis/HowToBuild@yanye666克隆回购协议并切换到此分支并按照这些说明）构建，我现在有一个二进制文件，我可以在应用程序文件夹中运行。公关审查和某种...测试;）。
> 
> @gnachman 请问这是晚上发生的事情吗？

MacOS 12 doesn't work. Can we ship a working "DMG" version

**Comment by saagarjha** [comment]
@yanye666 this will probably make it into a nightly soon, if a zip is fine with you

**Comment by yanye666** [comment]
> @yanye666 this will probably make it into a nightly soon, if a zip is fine with you

I need to install the package, I don’t need a zip, I don’t want to download xcode to compile

**Comment by gnachman** [comment]
> > @yanye666 this will probably make it into a nightly soon, if a zip is fine with you
> 
> I need to install the package, I don’t need a zip, I don’t want to download xcode to compile

https://iterm2.com/nightly/latest

**Pull request merged**
