### PR TITLE
Update preference pane icons for Yosemite

### PR DESCRIPTION
**Pull request by peteschaffner**
I love the current pref icons by @kaishin, but they were starting to feel a little out-of-date on Yosemite, so I riffed on them a bit. Let me know your thoughts.

screen shot 2015-03-22 at 8 48 59 pm

### CODE REVIEW

**Comment by gnachman** [comment]
Awesome! This is a much flatter look. The only thing that doesn't look quite right to me is the green background on Profiles. It draws too much attention, IMO. I love the green cursor in Appearance, though; it's a subtle callback to the icon.

Would you mind adding the source files you used (from Photoshop, Sketch, etc.) in case we need to tweak them later (e.g., add 3x assets).

**Comment by peteschaffner** [comment]
Yeah I agree, all that green was a bit much. I was inspired by the blue "@" account icons in a lot of Yosemite pref panels, but I think having a more uniform set feels better. Let me know what you think about this grey version.

image

**Comment by peteschaffner** [comment]
I cheated a  bit with the advanced icon, and just utilized the 64 and 32x32 cuts of the ToolbarAdvanced.icns from the CoreTypes.bundle. I would like to draw it eventually though, in case we want to tweak it some.

**Comment by peteschaffner** [comment]
A couple things I would like to work on before this gets merged:
- Flatten most icons out a bit more by toning down shadows and gradients
- Improve selection state on "Arrangements" icon (pixels with alpha channel don't get included in the highlight)
- Draw "Advanced" icon at a slightly smaller size to better fit with the scale of our set (or vice versa)

**Comment by gnachman** [comment]
Much better! I agree with your TODO list as well.

**Comment by kaishin** [comment]
Nice work @peteschaffner. I'd probably stick the Advanced icon used by other apps. Too bad the one that can be set in Xcode is not retina-optimized, so you have to include the asset in the app.

**Comment by peteschaffner** [comment]
Thanks @kaishin. Yeah, I noticed that too about the Advanced Xcode default icon. I agree, it is probably better to stick with the system standard as people are accustomed to it, but just for funs I drew a new one. I'm fine with reverting it though :)

Now with moar flat:
image

**Comment by gnachman** [comment]
Looking good! The old icons make me cringe when I look at them now. A
slightly scaled-down replica of the standard Advanced icon would be ideal,
but I like the one you drew too.

**Comment by peteschaffner** [comment]
Ok, I drew the system ToolbarAdvanced icon at a slightly scaled down size. I think I prefer it as well. I also played with the scale of the two circular icons a lot, but finally settled on this. Let me know your thoughts.
image

**Comment by kaishin** [comment]
This looks good to merge as far as I am concerned.

> The old icons make me cringe when I look at them now.

Mavericks as a whole does that to me now, including a lot of icons I designed.

**Comment by gnachman** [comment]
I loved your icons for a long time, @kaishin , didn't mean to slag on them :). But it's time to get flat up in here.

**Pull request merged**
