### PR TITLE
Added bindable key action to quickly toggle hotkey window pinning

### PR DESCRIPTION
**Pull request by allewun**
Resolves [issue 3413](https://code.google.com/p/iterm2/issues/detail?id=3413)

### CODE REVIEW

**Comment by gnachman** [comment]
I'm not persuaded that this feature is important enough to justify a menu item, but I'd be ok with it being a bindable key action.

**Comment by allewun** [comment]
I've implemented this as a bindable key action. One additional change I made was to have the hotkey window use `NSFloatingWindowLevel` when it loses focus and we don't autohide (aka "pinning"). Pinning wouldn't be very useful otherwise.

**Comment by gnachman** [comment]
Window level stuff is fraught with peril; let's leave that for another PR. I believe you will find endless issues with, for example, popup windows (e.g., autocomplete). Otherwise it looks good.

**Comment by allewun** [comment]
I tested popup windows and it worked fairly well for me, but I agree that the window stuff can get messy. Window level changes have been reverted, and I've squashed my commits.

**Comment by allewun** [comment]
@gnachman please have another look when you have a chance

**Comment by gnachman** [comment]
Thanks and sorry for the delay, looks good.

**Pull request merged**
