### PR TITLE
Fix regression focus after switching between apps

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by trufae** [comment]
Removing this code fixes the problem of rotating terminals when switching between apps. it's pretty anoying. I dont know why is this code here, so I'm just sending a PR for discussion. Feel free to fix that properly in your repo

**Comment by gnachman** [comment]
The goal of this code was to keep the window under the cursor active, since you might position the mouse and then cmd-tab to iTerm2. I guess when you cmd-tab out, move the mouse, and cmd-tab back you want to return to the window that used to be active, even if the mouse is no longer over it?

**Comment by trufae** [comment]
No need to move the cursor to reproduce this issue. Just open multiple iterm windows and ciclce between apps, everytime that iterm gets focus a different window is raised

**Comment by trufae** [comment]
Yep sounds reasonable but i should test the behaviour once fixed

Thanks

**Comment by gnachman** [comment]
Please test tomorrow's nightly build. The change is in commit 2b4e2f59

**Pull request closed without merging**
